[project]
name = "course-python-theory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Twoot", email = "inenquser@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
course-python-theory = "course_python_theory:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
