[project]
name = "course-python-theory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Twoot", email = "inenquser@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.14.3",
    "ruff>=0.16.4",
]

[project.scripts]
course-python-theory = "course_python_theory:main"

[tool.uv]
package = false
